#!/usr/bin/env python3
"""
Build site/leetcode/problems.json — the data behind the practice terminal.

For every problem in every bank this emits the statement, examples, constraints,
approach, complexity and the three language solutions, PLUS (best effort):

  · starter[lang]       a skeleton with the real signature + an entry point
  · solution_run[lang]  a complete, runnable program: solution + a demo main
                        that calls it with the first example's arguments

The demo is generated by matching the function parameters against the variable
names in the official example, so it only exists where it can be built safely —
problems we cannot parse simply ship without a runnable demo.

    python3 site/leetcode/build_bank_json.py
"""
from __future__ import annotations

import ast
import importlib.util
import json
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
SITE = HERE.parent
OUT = SITE / "leetcode" / "problems.json"

C_TYPES = {
    "int": lambda v: str(int(v)),
    "long": lambda v: str(int(v)),
    "unsigned": lambda v: str(int(v)),
    "long long": lambda v: f"{int(v)}LL",
    "short": lambda v: str(int(v)),
    "double": lambda v: f"{float(v)}",
    "float": lambda v: f"{float(v)}",
    "bool": lambda v: "true" if v else "false",
    "char": lambda v: "'" + str(v).replace("'", "\\'") + "'",
    "string": lambda v: '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"',
}

JAVA_TYPES = {
    "int": lambda v: str(int(v)),
    "long": lambda v: f"{int(v)}L",
    "short": lambda v: f"(short){int(v)}",
    "double": lambda v: f"{float(v)}",
    "float": lambda v: f"{float(v)}f",
    "boolean": lambda v: "true" if v else "false",
    "char": lambda v: "'" + str(v).replace("'", "\\'") + "'",
    "String": lambda v: '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"',
}

ARRAY_TYPES = {
    "int": "int", "long": "long", "short": "int", "double": "double",
    "float": "double", "boolean": "boolean", "char": "char", "String": "String",
}


# --------------------------------------------------------------------------- #
#  example parsing
# --------------------------------------------------------------------------- #
def parse_example_values(text: str) -> dict | None:
    """`nums = [1,2,3], k = 2` → {"nums": [1,2,3], "k": 2}  (None if unparseable)."""
    text = text.strip()
    if "=" not in text:
        return None
    values: dict[str, object] = {}
    # split on top-level commas
    parts, depth, quote, buf = [], 0, None, ""
    for ch in text:
        if quote:
            buf += ch
            if ch == quote:
                quote = None
            continue
        if ch in "\"'":
            quote = ch
            buf += ch
        elif ch in "[{(":
            depth += 1
            buf += ch
        elif ch in "]})":
            depth -= 1
            buf += ch
        elif ch == "," and depth == 0:
            parts.append(buf)
            buf = ""
        else:
            buf += ch
    parts.append(buf)
    for part in parts:
        if "=" not in part:
            return None
        name, _, raw = part.partition("=")
        name, raw = name.strip(), raw.strip()
        try:
            values[name] = ast.literal_eval(raw)
        except (ValueError, SyntaxError):
            try:
                values[name] = ast.literal_eval(str(int(raw)))         # plain numbers
            except (ValueError, SyntaxError):
                return None
    return values or None


# --------------------------------------------------------------------------- #
#  C++ demos
# --------------------------------------------------------------------------- #
def cpp_literal(type_name: str, value) -> str | None:
    t = " ".join(type_name.replace("&", " ").replace("*", " ").split())
    t = re.sub(r"\bconst\b", "", t).strip()
    if t.startswith("vector<") and t.endswith(">"):
        inner = t[len("vector<"):-1].strip()
        return cpp_vector_literal(inner, value)          # recurse element-wise
    if t in C_TYPES:
        try:
            return C_TYPES[t](value)
        except (TypeError, ValueError):
            return None
    if t.startswith("pair<") and t.endswith(">"):
        inner = t[len("pair<"):-1]
        split = [x.strip() for x in split_top(inner)]
        if len(split) == 2 and isinstance(value, (list, tuple)) and len(value) == 2:
            a, b = cpp_literal(split[0], value[0]), cpp_literal(split[1], value[1])
            if a and b:
                return "{" + a + ", " + b + "}"
    return None


def cpp_vector_literal(inner: str, values) -> str | None:
    if not isinstance(values, (list, tuple)):
        return None
    items = []
    for v in values:
        lit = cpp_literal(inner, v)
        if lit is None:
            return None
        items.append(lit)
    return "{" + ", ".join(items) + "}"


def split_top(text: str, sep: str = ",") -> list[str]:
    parts, depth, buf = [], 0, ""
    for ch in text:
        if ch in "<([{":
            depth += 1
            buf += ch
        elif ch in ">)]}":
            depth -= 1
            buf += ch
        elif ch == sep and depth == 0:
            parts.append(buf)
            buf = ""
        else:
            buf += ch
    parts.append(buf)
    return [p for p in parts if p.strip()]


def cpp_demo(code: str, example: str) -> str | None:
    if NODE_MARKERS.search(code) or JUDGE_APIS.search(code):
        return None
    values = parse_example_values(example)
    if not values:
        return None
    src = strip_comments(code)
    m = re.search(r"^([A-Za-z_][\w:<>,\s\*&\[\]]*?)\s+(\w+)\s*\(([^;{]*)\)\s*\{", src, re.M)
    if not m:
        return None
    ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
    if name in ("main",) or "Solution" in ret:
        return None
    args, decls, exprs = [], [], []
    for raw in split_top(params):
        bits = raw.strip().replace("const ", "").replace("&", "").strip()
        pieces = bits.split()
        if len(pieces) < 2:
            return None
        pname = pieces[-1].strip()
        ptype = " ".join(pieces[:-1])
        if pname not in values:
            return None
        value = values[pname]
        if ptype.startswith("vector<"):
            inner = ptype[len("vector<"):-1]
            lit = cpp_vector_literal(inner, value)
        else:
            lit = cpp_literal(ptype, value)
        if lit is None:
            return None
        decls.append(f"    {ptype} {pname} = {lit};")
        exprs.append(pname)
    printer = ""
    call = f"{name}({', '.join(exprs)})"
    ret_clean = re.sub(r"\b(static|inline)\b", "", ret).strip()
    if ret_clean == "void":
        body = f"    {call};"
    else:
        if "vector<" in ret_clean:
            printer = CPP_PRINTER
            body = f"    __pr({call});\n    cout << endl;"
        elif ret_clean in ("bool",):
            printer = CPP_PRINTER
            body = f"    __pr({call});\n    cout << endl;"
        elif ret_clean in ("string", "char"):
            printer = CPP_PRINTER
            body = f"    __pr({call});\n    cout << endl;"
        else:
            body = f"    cout << {call} << endl;"
    return ("\n\n" + printer + "\nint main() {\n" + "\n".join(decls) + "\n" + body + "\n    return 0;\n}\n").lstrip("\n")


CPP_PRINTER = """// --- demo printer -------------------------------------------------------
void __pr(long long x) { cout << x; }
void __pr(int x) { cout << x; }
void __pr(unsigned x) { cout << x; }
void __pr(double x) { cout << x; }
void __pr(bool x) { cout << (x ? "true" : "false"); }
void __pr(char x) { cout << '\\'' << x << '\\''; }
void __pr(const string& x) { cout << '"' << x << '"'; }
template <class T> void __pr(const vector<T>& v) {
    cout << '[';
    for (size_t i = 0; i < v.size(); i++) { if (i) cout << ','; __pr(v[i]); }
    cout << ']';
}
"""


# --------------------------------------------------------------------------- #
#  Java demos
# --------------------------------------------------------------------------- #
def java_literal(type_name: str, value) -> str | None:
    t = type_name.strip()
    if t.endswith("[][]"):
        base = t[:-4]
        if base not in ARRAY_TYPES or not isinstance(value, (list, tuple)):
            return None
        rows = []
        for row in value:
            lit = java_literal(base + "[]", row)
            if lit is None:
                return None
            rows.append(lit)
        return "new " + base + "[][]{" + ", ".join(rows) + "}"
    if t.endswith("[]"):
        base = t[:-2]
        if base not in ARRAY_TYPES or not isinstance(value, (list, tuple)):
            return None
        fn = JAVA_TYPES[base]
        items = []
        for v in value:
            try:
                items.append(fn(v))
            except (TypeError, ValueError):
                return None
        return "new " + base + "[]{" + ", ".join(items) + "}"
    if t in JAVA_TYPES:
        try:
            return JAVA_TYPES[t](value)
        except (TypeError, ValueError):
            return None
    return None


def java_demo(code: str, example: str) -> tuple[str, str] | None:
    """Returns (class-name, body of main) or None."""
    if NODE_MARKERS.search(code) or JUDGE_APIS.search(code):
        return None
    values = parse_example_values(example)
    if not values:
        return None
    src = strip_comments(code, java=True)
    m = re.search(r"(?:public\s+|private\s+|protected\s+)?(?:static\s+)?"
                  r"([A-Za-z_][\w<>\[\],\s]*?)\s+(\w+)\s*\(([^)]*)\)\s*\{", src)
    if not m:
        return None
    ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
    if name in ("main",) or name in ("Solution",):
        return None
    if ret in ("class", "interface", "void") and name[0].islower() and ret == "void":
        pass
    decls, exprs = [], []
    for raw in split_top(params):
        bits = raw.strip().replace("final ", "").strip()
        pieces = bits.split()
        if len(pieces) < 2:
            return None
        pname = pieces[-1]
        ptype = " ".join(pieces[:-1])
        if pname not in values:
            return None
        lit = java_literal(ptype, values[pname])
        if lit is None:
            return None
        decls.append(f"        {ptype} {pname} = {lit};")
        exprs.append(pname)
    call = f"new Main().{name}({', '.join(exprs)})"
    if ret == "void":
        body = [f"        {call};"]
    elif ret.endswith("[][]"):
        body = [f"        System.out.println(java.util.Arrays.deepToString({call}));"]
    elif ret.endswith("[]"):
        base = ret[:-2]
        printer = "toString" if base in ("int", "long", "short", "double", "float",
                                        "boolean", "char", "byte") else "deepToString"
        body = [f"        System.out.println(java.util.Arrays.{printer}({call}));"]
    elif ret == "boolean":
        body = [f"        System.out.println({call});"]
    elif ret in ("char", "String"):
        body = [f"        System.out.println({call});"]
    else:
        body = [f"        System.out.println({call});"]
    return ("Main", decls + body)


# --------------------------------------------------------------------------- #
#  Python demos
# --------------------------------------------------------------------------- #
PY_IMPORTS = [
    (r"\b(bisect_left|bisect_right|bisect)\b", "from bisect import bisect_left, bisect_right, bisect"),
    (r"\b(defaultdict|deque|Counter|OrderedDict)\b",
     "from collections import defaultdict, deque, Counter, OrderedDict"),
    (r"\b(heappush|heappop|heapify|nlargest|nsmallest|heapreplace|heappushpop)\b", "import heapq"),
    (r"\b(lru_cache|cache|reduce)\b", "from functools import lru_cache, cache, reduce"),
    (r"\b(combinations|permutations|product|combinations_with_replacement)\b", "from itertools import combinations, permutations, product"),
    (r"\b(accumulate|groupby)\b", "from itertools import accumulate, groupby"),
    (r"\b(isqrt|floor|ceil|gcd|comb|factorial|perm)\b", "from math import isqrt, floor, ceil, gcd, comb, factorial, perm"),
    (r"\b(inf|log|sqrt|log2|pow)\b", "import math"),
    (r"\bre\.", "import re"),
    (r"\bint\(.*, *16\)", "import sys"),
]


def python_prelude(code: str) -> str:
    """The bank snippets rely on the judge's namespace for a few helpers; a real
    interpreter needs the imports written out."""
    needed = []
    for pattern, line in PY_IMPORTS:
        if re.search(pattern, code):
            module = line.split()[1].split(".")[0] if line.startswith("from") else line.split()[1]
            if re.search(r"^\s*(?:from\s+" + module + r"\s+import|import\s+" + module + r"\b)", code, re.M):
                continue
            needed.append(line)
    return "\n".join(needed) + ("\n\n" if needed else "")

NODE_MARKERS = re.compile(r"\b(TreeNode|ListNode|Node|TreeLinkNode)\b")
# APIs the judge provides (declared in a snippet but never defined) — a demo
# program cannot link or run against them, so those problems ship without one.
JUDGE_APIS = re.compile(r"\b(isBadVersion|is_bad_version|guess|MountainArray|read4|Reader4|NestedInteger|ArrayReader|Master|Sea)\b")


def python_demo(code: str, example: str, other_langs: str = "") -> str | None:
    # The example is a serialised tree / linked list / graph when any language's
    # solution mentions a node type — a Python signature alone cannot show that.
    if NODE_MARKERS.search(code) or NODE_MARKERS.search(other_langs) or JUDGE_APIS.search(code):
        return None
    values = parse_example_values(example)
    if not values:
        return None
    src = strip_comments(code, python=True)
    m = re.search(r"^def\s+(\w+)\s*\(([^)]*)\)\s*:", src, re.M)
    if not m:
        return None
    name, params = m.group(1), m.group(2)
    args = []
    for raw in split_top(params):
        arg = raw.strip().split(":")[0].split("=")[0].strip()
        if arg in ("self", "cls") or not arg:
            if arg in ("self", "cls"):
                return None
            continue
        if arg not in values:
            return None
        args.append(repr(values[arg]))
    return (f"_result = {name}({', '.join(args)})\n"
            f"if _result is not None:\n"
            f"    print(_result)")


# --------------------------------------------------------------------------- #
#  helpers
# --------------------------------------------------------------------------- #
def strip_comments(code: str, java: bool = False, python: bool = False) -> str:
    code = re.sub(r"/\*.*?\*/", "", code, flags=re.S)
    if python:
        return "".join(line.split("#")[0] + "\n" for line in code.splitlines())
    code = re.sub(r"//[^\n]*", "", code)
    return code


def first_python_signature(code: str) -> str | None:
    for line in code.splitlines():
        line = line.strip()
        if line.startswith("def "):
            return line.rstrip(":")
    return None


PY_STARTER = '''import sys

def solve():
    data = sys.stdin.read().split()
    # TODO: read the input the way the problem describes, then print the answer
    print(0)

if __name__ == "__main__":
    solve()
'''

CPP_STARTER = '''int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    // TODO: read the input, compute, print the answer
    cout << 0 << '\\n';
    return 0;
}
'''

JAVA_STARTER = '''public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        // TODO: read the input, compute, print the answer
        System.out.println(0);
    }
}
'''


def python_starter(solution: str) -> str:
    sig = first_python_signature(solution)
    if not sig:
        return PY_STARTER
    body = f"""
{sig}:
    # TODO: implement
    pass


if __name__ == "__main__":
    # Example: turn the first sample into a call and print the result.
    print(solve())
"""
    return body.lstrip("\n")


def java_starter(solution: str) -> str:
    src = strip_comments(solution, java=True)
    m = re.search(r"^[\t ]*(?:public\s+|private\s+|protected\s+)?(?:static\s+)?"
                  r"([A-Za-z_][\w<>\[\],\s]*?)\s+(\w+)\s*\(([^)]*)\)\s*\{", src, re.M)
    if not m:
        return JAVA_STARTER
    ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
    return (f"public class Main {{\n"
            f"    // {ret} {name}({params}) — implement this\n"
            f"    {'static ' if 'static' in solution[:m.start()] else ''}{ret} {name}({params}) {{\n"
            f"        // TODO\n"
            f"        return {'null' if not ret.islower() or ret in ('int', 'long', 'short', 'double', 'float') else 'false'};\n"
            f"    }}\n"
            f"}}\n")


def cpp_starter(solution: str) -> str:
    src = strip_comments(solution)
    m = re.search(r"^([A-Za-z_][\w:<>,\s\*&\[\]]*?)\s+(\w+)\s*\(([^;{]*)\)\s*\{", src, re.M)
    if not m:
        return CPP_STARTER
    ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
    return (f"{ret} {name}({params}) {{\n"
            f"    // TODO\n"
            f"    return {ret.rstrip('&')}{{}};\n"
            f"}}\n\n"
            f"int main() {{\n"
            f"    // call {name}(...) with the sample arguments and print the result\n"
            f"    return 0;\n"
            f"}}\n")


# --------------------------------------------------------------------------- #
#  main
# --------------------------------------------------------------------------- #
def main() -> int:
    banks = []
    for path in sorted(HERE.glob("bank_*.py")):
        spec = importlib.util.spec_from_file_location(path.stem, path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)              # type: ignore[union-attr]
        banks.append({"topic": mod.TOPIC, "problems": mod.PROBLEMS})

    topics, problems = [], []
    stats = {"total": 0, "demo_py": 0, "demo_cpp": 0, "demo_java": 0}
    for ti, bank in enumerate(banks, 1):
        topics.append({"n": ti, "name": bank["topic"]["name"], "tagline": bank["topic"]["tagline"]})
        for prob in bank["problems"]:
            stats["total"] += 1
            example = prob["examples"][0][0] if prob.get("examples") else ""
            entry = {
                "slug": prob["slug"], "title": prob["title"], "difficulty": prob["difficulty"],
                "topic_n": ti, "topic": bank["topic"]["name"], "pattern": prob["pattern"],
                "statement": prob["statement"], "examples": prob.get("examples", []),
                "constraints": prob.get("constraints", []), "approach": prob["approach"],
                "complexity": list(prob["complexity"]),
                "code": {k: prob["code"][k] for k in ("cpp", "java", "python")},
                "starter": {}, "solution_run": {},
            }
            # ---- python
            demo = python_demo(prob["code"]["python"], example,
                               prob["code"]["cpp"] + prob["code"]["java"])
            entry["starter"]["python"] = python_starter(prob["code"]["python"])
            if demo:
                body = prob["code"]["python"].rstrip()
                entry["solution_run"]["python"] = python_prelude(body) + body + "\n\n" + demo + "\n"
                stats["demo_py"] += 1
            # ---- c++
            demo_cpp = cpp_demo(prob["code"]["cpp"], example)
            entry["starter"]["cpp"] = cpp_starter(prob["code"]["cpp"])
            if demo_cpp:
                entry["solution_run"]["cpp"] = prob["code"]["cpp"].rstrip() + "\n\n" + demo_cpp
                stats["demo_cpp"] += 1
            # ---- java
            demo_java = java_demo(prob["code"]["java"], example)
            entry["starter"]["java"] = java_starter(prob["code"]["java"])
            if demo_java:
                _, body = demo_java
                entry["solution_run"]["java"] = ("import java.util.*;\n\n"
                                                 "public class Main {\n"
                                                 + prob["code"]["java"].rstrip() + "\n\n"
                                                 "    public static void main(String[] args) {\n"
                                                 + "\n".join(body) + "\n"
                                                 "    }\n}\n")
                stats["demo_java"] += 1
            problems.append(entry)

    payload = {"count": len(problems), "topics": topics, "problems": problems,
               "demos": {"python": stats["demo_py"], "cpp": stats["demo_cpp"], "java": stats["demo_java"]}}
    OUT.write_text(json.dumps(payload, separators=(",", ":"), ensure_ascii=False))
    print(f"wrote {OUT.relative_to(SITE.parent)}  ({OUT.stat().st_size/1024/1024:.2f} MB)")
    print(f"  problems: {stats['total']}")
    print(f"  runnable demos: python {stats['demo_py']}/{stats['total']}"
          f" · c++ {stats['demo_cpp']}/{stats['total']} · java {stats['demo_java']}/{stats['total']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
