#!/usr/bin/env python3
"""
Build site/leetcode/problems.json — the data behind the practice terminal.

For every problem in every bank this emits the statement, examples, constraints,
approach, complexity and the three language solutions, PLUS (best effort):

  · starter[lang]       a skeleton with the real signature + an entry point
  · solution_run[lang]  a complete, runnable program: solution + a demo main
                        that calls it with the first example's arguments

The demo is generated by matching the function parameters against the variable
names in the official example, so it only exists where it can be built safely —
problems we cannot parse simply ship without a runnable demo.

    python3 site/leetcode/build_bank_json.py
"""
from __future__ import annotations

import ast
import importlib.util
import json
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
SITE = HERE.parent
OUT = SITE / "leetcode" / "problems.json"

C_TYPES = {
    "int": lambda v: str(int(v)),
    "long": lambda v: str(int(v)),
    "unsigned": lambda v: str(int(v)),
    "long long": lambda v: f"{int(v)}LL",
    "short": lambda v: str(int(v)),
    "double": lambda v: f"{float(v)}",
    "float": lambda v: f"{float(v)}",
    "bool": lambda v: "true" if v else "false",
    "char": lambda v: "'" + str(v).replace("'", "\\'") + "'",
    "string": lambda v: '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"',
}

JAVA_TYPES = {
    "int": lambda v: str(int(v)),
    "long": lambda v: f"{int(v)}L",
    "short": lambda v: f"(short){int(v)}",
    "double": lambda v: f"{float(v)}",
    "float": lambda v: f"{float(v)}f",
    "boolean": lambda v: "true" if v else "false",
    "char": lambda v: "'" + str(v).replace("'", "\\'") + "'",
    "String": lambda v: '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"',
}

ARRAY_TYPES = {
    "int": "int", "long": "long", "short": "int", "double": "double",
    "float": "double", "boolean": "boolean", "char": "char", "String": "String",
}


# --------------------------------------------------------------------------- #
#  example parsing
# --------------------------------------------------------------------------- #
def parse_example_values(text: str) -> dict | None:
    """`nums = [1,2,3], k = 2` → {"nums": [1,2,3], "k": 2}  (None if unparseable)."""
    text = text.strip()
    if "=" not in text:
        return None
    values: dict[str, object] = {}
    # split on top-level commas
    parts, depth, quote, buf = [], 0, None, ""
    for ch in text:
        if quote:
            buf += ch
            if ch == quote:
                quote = None
            continue
        if ch in "\"'":
            quote = ch
            buf += ch
        elif ch in "[{(":
            depth += 1
            buf += ch
        elif ch in "]})":
            depth -= 1
            buf += ch
        elif ch == "," and depth == 0:
            parts.append(buf)
            buf = ""
        else:
            buf += ch
    parts.append(buf)
    for part in parts:
        if "=" not in part:
            return None
        name, _, raw = part.partition("=")
        name, raw = name.strip(), raw.strip()
        try:
            values[name] = ast.literal_eval(raw)
        except (ValueError, SyntaxError):
            try:
                values[name] = ast.literal_eval(str(int(raw)))         # plain numbers
            except (ValueError, SyntaxError):
                return None
    return values or None


# --------------------------------------------------------------------------- #
#  C++ demos
# --------------------------------------------------------------------------- #
def cpp_literal(type_name: str, value) -> str | None:
    t = " ".join(type_name.replace("&", " ").replace("*", " ").split())
    t = re.sub(r"\bconst\b", "", t).strip()
    if t.startswith("vector<") and t.endswith(">"):
        inner = t[len("vector<"):-1].strip()
        return cpp_vector_literal(inner, value)          # recurse element-wise
    if t in C_TYPES:
        try:
            return C_TYPES[t](value)
        except (TypeError, ValueError):
            return None
    if t.startswith("pair<") and t.endswith(">"):
        inner = t[len("pair<"):-1]
        split = [x.strip() for x in split_top(inner)]
        if len(split) == 2 and isinstance(value, (list, tuple)) and len(value) == 2:
            a, b = cpp_literal(split[0], value[0]), cpp_literal(split[1], value[1])
            if a and b:
                return "{" + a + ", " + b + "}"
    return None


def cpp_vector_literal(inner: str, values) -> str | None:
    if not isinstance(values, (list, tuple)):
        return None
    items = []
    for v in values:
        lit = cpp_literal(inner, v)
        if lit is None:
            return None
        items.append(lit)
    return "{" + ", ".join(items) + "}"


def split_top(text: str, sep: str = ",") -> list[str]:
    parts, depth, buf, quote = [], 0, "", None
    for ch in text:
        if quote:
            buf += ch
            if ch == quote:
                quote = None
            continue
        if ch in "\"'":
            quote = ch
            buf += ch
        elif ch in "<([{":
            depth += 1
            buf += ch
        elif ch in ">)]}":
            depth -= 1
            buf += ch
        elif ch == sep and depth == 0:
            parts.append(buf)
            buf = ""
        else:
            buf += ch
    parts.append(buf)
    return [p for p in parts if p.strip()]


def cpp_demo(code: str, example: str) -> str | None:
    if NODE_MARKERS.search(code) or JUDGE_APIS.search(code):
        return None
    values = parse_example_values(example)
    if not values:
        return None
    src = strip_comments(code)
    m = re.search(r"^([A-Za-z_][\w:<>,\s\*&\[\]]*?)\s+(\w+)\s*\(([^;{]*)\)\s*\{", src, re.M)
    if not m:
        return None
    ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
    if name in ("main",) or "Solution" in ret:
        return None
    args, decls, exprs = [], [], []
    for raw in split_top(params):
        bits = raw.strip().replace("const ", "").replace("&", "").strip()
        pieces = bits.split()
        if len(pieces) < 2:
            return None
        pname = pieces[-1].strip()
        ptype = " ".join(pieces[:-1])
        if pname not in values:
            return None
        value = values[pname]
        if ptype.startswith("vector<"):
            inner = ptype[len("vector<"):-1]
            lit = cpp_vector_literal(inner, value)
        else:
            lit = cpp_literal(ptype, value)
        if lit is None:
            return None
        decls.append(f"    {ptype} {pname} = {lit};")
        exprs.append(pname)
    printer = ""
    call = f"{name}({', '.join(exprs)})"
    ret_clean = re.sub(r"\b(static|inline)\b", "", ret).strip()
    if ret_clean == "void":
        body = f"    {call};"
    else:
        if "vector<" in ret_clean:
            printer = CPP_PRINTER
            body = f"    __pr({call});\n    cout << endl;"
        elif ret_clean in ("bool",):
            printer = CPP_PRINTER
            body = f"    __pr({call});\n    cout << endl;"
        elif ret_clean in ("string", "char"):
            printer = CPP_PRINTER
            body = f"    __pr({call});\n    cout << endl;"
        else:
            body = f"    cout << {call} << endl;"
    return ("\n\n" + printer + "\nint main() {\n" + "\n".join(decls) + "\n" + body + "\n    return 0;\n}\n").lstrip("\n")


CPP_PRINTER = """// --- demo printer -------------------------------------------------------
void __pr(long long x) { cout << x; }
void __pr(int x) { cout << x; }
void __pr(unsigned x) { cout << x; }
void __pr(double x) { cout << x; }
void __pr(bool x) { cout << (x ? "true" : "false"); }
void __pr(char x) { cout << '\\'' << x << '\\''; }
void __pr(const string& x) { cout << '"' << x << '"'; }
template <class T> void __pr(const vector<T>& v) {
    cout << '[';
    for (size_t i = 0; i < v.size(); i++) { if (i) cout << ','; __pr(v[i]); }
    cout << ']';
}
"""


# --------------------------------------------------------------------------- #
#  Java demos
# --------------------------------------------------------------------------- #
def java_literal(type_name: str, value) -> str | None:
    t = type_name.strip()
    if t.endswith("[][]"):
        base = t[:-4]
        if base not in ARRAY_TYPES or not isinstance(value, (list, tuple)):
            return None
        rows = []
        for row in value:
            lit = java_literal(base + "[]", row)
            if lit is None:
                return None
            rows.append(lit)
        return "new " + base + "[][]{" + ", ".join(rows) + "}"
    if t.endswith("[]"):
        base = t[:-2]
        if base not in ARRAY_TYPES or not isinstance(value, (list, tuple)):
            return None
        fn = JAVA_TYPES[base]
        items = []
        for v in value:
            try:
                items.append(fn(v))
            except (TypeError, ValueError):
                return None
        return "new " + base + "[]{" + ", ".join(items) + "}"
    if t in JAVA_TYPES:
        try:
            return JAVA_TYPES[t](value)
        except (TypeError, ValueError):
            return None
    return None


def java_demo(code: str, example: str) -> tuple[str, str] | None:
    """Returns (class-name, body of main) or None."""
    if NODE_MARKERS.search(code) or JUDGE_APIS.search(code):
        return None
    values = parse_example_values(example)
    if not values:
        return None
    src = strip_comments(code, java=True)
    m = re.search(r"(?:public\s+|private\s+|protected\s+)?(?:static\s+)?"
                  r"([A-Za-z_][\w<>\[\],\s]*?)\s+(\w+)\s*\(([^)]*)\)\s*\{", src)
    if not m:
        return None
    ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
    if name in ("main",) or name in ("Solution",):
        return None
    if ret in ("class", "interface", "void") and name[0].islower() and ret == "void":
        pass
    decls, exprs = [], []
    for raw in split_top(params):
        bits = raw.strip().replace("final ", "").strip()
        pieces = bits.split()
        if len(pieces) < 2:
            return None
        pname = pieces[-1]
        ptype = " ".join(pieces[:-1])
        if pname not in values:
            return None
        lit = java_literal(ptype, values[pname])
        if lit is None:
            return None
        decls.append(f"        {ptype} {pname} = {lit};")
        exprs.append(pname)
    call = f"new Main().{name}({', '.join(exprs)})"
    if ret == "void":
        body = [f"        {call};"]
    elif ret.endswith("[][]"):
        body = [f"        System.out.println(java.util.Arrays.deepToString({call}));"]
    elif ret.endswith("[]"):
        base = ret[:-2]
        printer = "toString" if base in ("int", "long", "short", "double", "float",
                                        "boolean", "char", "byte") else "deepToString"
        body = [f"        System.out.println(java.util.Arrays.{printer}({call}));"]
    elif ret == "boolean":
        body = [f"        System.out.println({call});"]
    elif ret in ("char", "String"):
        body = [f"        System.out.println({call});"]
    else:
        body = [f"        System.out.println({call});"]
    return ("Main", decls + body)


# --------------------------------------------------------------------------- #
#  Python demos
# --------------------------------------------------------------------------- #
PY_IMPORTS = [
    (r"\b(bisect_left|bisect_right|bisect)\b", "from bisect import bisect_left, bisect_right, bisect"),
    (r"\b(defaultdict|deque|Counter|OrderedDict)\b",
     "from collections import defaultdict, deque, Counter, OrderedDict"),
    (r"\b(heappush|heappop|heapify|nlargest|nsmallest|heapreplace|heappushpop)\b", "import heapq"),
    (r"\b(lru_cache|cache|reduce)\b", "from functools import lru_cache, cache, reduce"),
    (r"\b(combinations|permutations|product|combinations_with_replacement)\b", "from itertools import combinations, permutations, product"),
    (r"\b(accumulate|groupby)\b", "from itertools import accumulate, groupby"),
    (r"\b(isqrt|floor|ceil|gcd|comb|factorial|perm)\b", "from math import isqrt, floor, ceil, gcd, comb, factorial, perm"),
    (r"\b(inf|log|sqrt|log2|pow)\b", "import math"),
    (r"\bre\.", "import re"),
    (r"\bint\(.*, *16\)", "import sys"),
]


def python_prelude(code: str) -> str:
    """The bank snippets rely on the judge's namespace for a few helpers; a real
    interpreter needs the imports written out."""
    needed = []
    for pattern, line in PY_IMPORTS:
        if re.search(pattern, code):
            module = line.split()[1].split(".")[0] if line.startswith("from") else line.split()[1]
            if re.search(r"^\s*(?:from\s+" + module + r"\s+import|import\s+" + module + r"\b)", code, re.M):
                continue
            needed.append(line)
    return "\n".join(needed) + ("\n\n" if needed else "")

NODE_MARKERS = re.compile(r"\b(TreeNode|ListNode|Node|TreeLinkNode)\b")
# APIs the judge provides (declared in a snippet but never defined) — a demo
# program cannot link or run against them, so those problems ship without one.
JUDGE_APIS = re.compile(r"\b(isBadVersion|is_bad_version|guess|MountainArray|read4|Reader4|NestedInteger|ArrayReader|Master|Sea)\b")


def python_demo(code: str, example: str, other_langs: str = "") -> str | None:
    # The example is a serialised tree / linked list / graph when any language's
    # solution mentions a node type — a Python signature alone cannot show that.
    if NODE_MARKERS.search(code) or NODE_MARKERS.search(other_langs) or JUDGE_APIS.search(code):
        return None
    values = parse_example_values(example)
    if not values:
        return None
    src = strip_comments(code, python=True)
    m = re.search(r"^def\s+(\w+)\s*\(([^)]*)\)\s*:", src, re.M)
    if not m:
        return None
    name, params = m.group(1), m.group(2)
    args = []
    for raw in split_top(params):
        arg = raw.strip().split(":")[0].split("=")[0].strip()
        if arg in ("self", "cls") or not arg:
            if arg in ("self", "cls"):
                return None
            continue
        if arg not in values:
            return None
        args.append(repr(values[arg]))
    return (f"_result = {name}({', '.join(args)})\n"
            f"if _result is not None:\n"
            f"    print(_result)")


# --------------------------------------------------------------------------- #
#  helpers
# --------------------------------------------------------------------------- #
def strip_comments(code: str, java: bool = False, python: bool = False) -> str:
    code = re.sub(r"/\*.*?\*/", "", code, flags=re.S)
    if python:
        return "".join(line.split("#")[0] + "\n" for line in code.splitlines())
    code = re.sub(r"//[^\n]*", "", code)
    return code


def first_python_signature(code: str) -> str | None:
    for line in code.splitlines():
        line = line.strip()
        if line.startswith("def "):
            return line.rstrip(":")
    return None


PY_STARTER = '''import sys

def solve():
    data = sys.stdin.read().split()
    # TODO: read the input the way the problem describes, then print the answer
    print(0)

if __name__ == "__main__":
    solve()
'''

CPP_STARTER = '''int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    // TODO: read the input, compute, print the answer
    cout << 0 << '\\n';
    return 0;
}
'''

JAVA_STARTER = '''public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        // TODO: read the input, compute, print the answer
        System.out.println(0);
    }
}
'''


def python_starter(solution: str) -> str:
    sig = first_python_signature(solution)
    if not sig:
        return PY_STARTER
    body = f"""
{sig}:
    # TODO: implement
    pass


if __name__ == "__main__":
    # Example: turn the first sample into a call and print the result.
    print(solve())
"""
    return body.lstrip("\n")


def java_starter(solution: str) -> str:
    src = strip_comments(solution, java=True)
    m = re.search(r"^[\t ]*(?:public\s+|private\s+|protected\s+)?(?:static\s+)?"
                  r"([A-Za-z_][\w<>\[\],\s]*?)\s+(\w+)\s*\(([^)]*)\)\s*\{", src, re.M)
    if not m:
        return JAVA_STARTER
    ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
    return (f"public class Main {{\n"
            f"    // {ret} {name}({params}) — implement this\n"
            f"    {'static ' if 'static' in solution[:m.start()] else ''}{ret} {name}({params}) {{\n"
            f"        // TODO\n"
            f"        return {'null' if not ret.islower() or ret in ('int', 'long', 'short', 'double', 'float') else 'false'};\n"
            f"    }}\n"
            f"}}\n")


def cpp_starter(solution: str) -> str:
    src = strip_comments(solution)
    m = re.search(r"^([A-Za-z_][\w:<>,\s\*&\[\]]*?)\s+(\w+)\s*\(([^;{]*)\)\s*\{", src, re.M)
    if not m:
        return CPP_STARTER
    ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
    return (f"{ret} {name}({params}) {{\n"
            f"    // TODO\n"
            f"    return {ret.rstrip('&')}{{}};\n"
            f"}}\n\n"
            f"int main() {{\n"
            f"    // call {name}(...) with the sample arguments and print the result\n"
            f"    return 0;\n"
            f"}}\n")


# --------------------------------------------------------------------------- #
#  C demos
# --------------------------------------------------------------------------- #
C_SCALAR = {"int": "%lld", "long": "%lld", "long long": "%lld", "short": "%lld",
            "unsigned": "%llu", "unsigned int": "%llu", "size_t": "%llu",
            "double": "%g", "float": "%g", "char": "%c"}
SIZE_ROLE = ("returnsize", "returncolumnsize", "outsize")


def c_base_type(param: str) -> tuple[str, str, int]:
    """`const int *nums` → ("int", "nums", 1).  ("", "", 0) when it is not plain C."""
    t = re.sub(r"\b(const|volatile|restrict|static|register)\b", " ", param)
    t = " ".join(t.split())
    if t in ("void", ""):
        return ("void", "", 0)
    m = re.match(r"^(.*?)(\s*\*+\s*|\s+)(\w+)\s*((?:\[[^\]]*\])*)$", t)
    if not m:
        return ("", "", 0)
    head, stars, name, arr = m.group(1).strip(), m.group(2), m.group(3), m.group(4)
    ptr = stars.count("*") + len(re.findall(r"\[[^\]]*\]", arr))
    head = re.sub(r"\b(struct|enum|union)\s+(\w+)", r"\2", head).strip()
    return (head, name, ptr)


def c_example_values(params: str, example: str) -> dict | None:
    """The example's values, keyed by parameter name.

    The banks mix three styles, so all three are understood:
        nums = [2,7,11,15], target = 9      named
        [3, 1, 9, 4, 9]                     positional, with numsSize / n implied
        [[1,2,3],[4,5,6]], k = 2            mixed, and matrix dimensions implied
    """
    sig = [c_base_type(p) for p in split_top(params)]
    positional: list = []
    named: dict = {}
    for raw in split_top(example):
        txt = raw.strip()
        if "=" in txt:
            key, _, val = txt.partition("=")
            try:
                named[key.strip()] = ast.literal_eval(val.strip())
            except (ValueError, SyntaxError):
                return None
        else:
            # a trailing line like "0   (the answer)" is commentary, not a value
            try:
                positional.append(ast.literal_eval(txt))
            except (ValueError, SyntaxError):
                if named:
                    break
                return None
    if not positional and not named:
        return None

    def dims_of(value) -> list[int]:
        dims = []
        while isinstance(value, list):
            dims.append(len(value))
            value = value[0] if value else None
        return dims

    out: dict = {}
    last_array = None
    k = 0
    pending_dims = 0
    for base, pname, ptr in sig:
        if base == "void" and not pname:
            continue
        low = pname.lower()
        if ptr and (low in SIZE_ROLE or low.endswith(("count", "size", "length"))):
            continue                                     # filled by the call itself
        if pname in named:
            out[pname] = named[pname]
            if ptr:
                last_array = pname
            continue
        if not ptr and base in ("int", "unsigned", "size_t", "long", "long long"):
            if last_array and not isinstance(out.get(last_array), tuple):
                tails = (last_array.lower() + "size", last_array.lower() + "len",
                         last_array.lower() + "length", "n", "size")
                if low in tails:
                    out[pname] = ("__len__", last_array)
                    continue
            nxt = positional[k] if k < len(positional) else None
            if isinstance(nxt, list):
                dims = dims_of(nxt)
                if pending_dims < len(dims):
                    out[pname] = ("__num__", dims[pending_dims])   # rows, then cols
                    pending_dims += 1
                    continue
            if nxt is None and last_array and not isinstance(out.get(last_array), tuple):
                out[pname] = ("__len__", last_array)               # median(a, n, b, m)
                continue
            return None
        if k < len(positional):
            out[pname] = positional[k]
            k += 1
        elif ptr:
            out[pname] = ("__buffer__", base)              # an output the call fills in
        else:
            return None
        if ptr:
            last_array = pname
            pending_dims = 0
    # an unfilled pointer is only believable as an output buffer when nothing after it
    # depends on it (otherwise the signature and the example simply do not match)
    names = [p for _, p, _ in sig if p]
    for index, (base, pname, ptr) in enumerate(sig):
        if not ptr or not isinstance(out.get(pname), tuple):
            continue
        for _, later, lptr in sig[index + 1:]:
            if later and (later.lower() in SIZE_ROLE or later.lower().endswith(("count", "size", "length"))):
                continue
            return None
    return out


def c_show_mutated(args: list[str], values: dict, sizes: dict) -> list[str]:
    """`printf` lines that show the first array / matrix / string the call worked on."""
    for name in args:
        value = values.get(name)
        if isinstance(value, tuple):
            continue
        if isinstance(value, str):
            return [f'    printf("%s\\n", {name});']
        if isinstance(value, list) and value and all(isinstance(x, list) for x in value):
            rows = sizes.get(name, "0")
            cols = sizes.get("__cols_" + name, "0")
            return [f'    for (int i = 0; i < {rows}; i++) {{',
                    '        printf("[");',
                    f'        for (int j = 0; j < {cols}; j++) printf(j ? ",%lld" : "%lld", (long long) {name}[i][j]);',
                    '        printf(i + 1 < ' + rows + ' ? "], " : "]");',
                    '    }',
                    '    printf("\\n");']
        if isinstance(value, list):
            length = sizes.get(name, "0")
            return ['    printf("[");',
                    f'    for (int i = 0; i < {length}; i++) printf(i ? ",%lld" : "%lld", (long long) {name}[i]);',
                    '    printf("]\\n");']
    return []


C_SIGNATURE = re.compile(r"^([A-Za-z_][A-Za-z_0-9 \t*]*?)\s*(\**\s*\w+)\s*\(([^;{]*)\)\s*\{", re.M)


def c_signatures(src: str) -> list[tuple[str, str, str, bool]]:
    """(return type, name, params, is_static) for every function defined in `src`."""
    found = []
    for m in C_SIGNATURE.finditer(src):
        head = " ".join(m.group(1).split())
        if head in ("if", "for", "while", "switch", "else", "return", "sizeof", "do"):
            continue
        stars = m.group(2)[:len(m.group(2)) - len(m.group(2).lstrip("*"))]
        name = m.group(2).lstrip("* ").strip()
        ret = (head + " " + stars).strip()
        if name in ("main",) or "Solution" in ret:
            continue
        found.append((ret, name, m.group(3), "static" in ret))
    return found


def c_demo(code: str, example: str, expected: str = "") -> str | None:
    """A runnable C `main` for the first example — or None when C is a poor fit."""
    if NODE_MARKERS.search(code) or JUDGE_APIS.search(code):
        return None
    src = strip_comments(code)
    if "->" in src or re.search(r"\bstruct\b", src):
        return None                                  # linked lists, trees, tries, design classes
    signatures = c_signatures(src)
    # helpers marked static come first in some files, so try the public ones before them
    signatures.sort(key=lambda t: t[3])
    for ret, name, params, _ in signatures:
        built = c_demo_from_signature(ret, name, params, example, expected)
        if built:
            return built
    return None


def c_demo_from_signature(ret_in: str, name: str, params: str, example: str, expected: str = "") -> str | None:
    ret_raw = re.sub(r"\b(static|inline)\b", " ", ret_in).strip()
    ret_t, ret_ptr = c_base_type(ret_raw + " __ret")[0], ret_raw.count("*")
    values = c_example_values(params, example)
    if not values:
        return None

    rows_prefix: list[str] = []      # matrix rows, declared before the row-pointer arrays
    buffers: list[str] = []          # output buffers filled in by the call
    decls: list[str] = []            # declarations in parameter order
    sizes: dict[str, str] = {}       # declared name → its length expression
    args: list[str] = []
    out_size = None                  # a `*returnSize` style parameter, if any

    for raw in split_top(params):
        base, pname, ptr = c_base_type(raw)
        if base == "void" and not pname:
            continue                       # `int f(void)`
        if not pname or not base:
            return None
        low = pname.lower()
        if ptr and (low in SIZE_ROLE or low.endswith(("count", "size", "length"))):
            out_size = pname                              # `int *outCount`, `int *returnSize`, …
            args.append("&" + pname)
            continue
        if base == "void":
            return None                                   # `const void *` helpers need casts
        value = values.get(pname)
        if value is None:
            return None

        # a dimension the example implies: rows / cols of a matrix
        if isinstance(value, tuple) and len(value) == 2 and value[0] == "__num__":
            decls.append(f"    int {pname} = {value[1]};")
            args.append(pname)
            continue

        # a size the example leaves implicit: numsSize / wordLen / n / size
        if isinstance(value, tuple) and len(value) == 2 and value[0] == "__len__":
            if value[1] not in sizes:
                return None
            decls.append(f"    int {pname} = {sizes[value[1]]};")
            sizes[pname] = sizes[value[1]]
            args.append(pname)
            continue

        if isinstance(value, tuple) and len(value) == 2 and value[0] == "__buffer__":
            kind = base if base in ("int", "long", "long long", "char", "double") else "int"
            decls.append(f"    {kind} {pname}[512];")          # the call fills this in
            sizes[pname] = "512"
            buffers.append(pname)
            args.append(pname)
            continue
        if ptr >= 2:
            if isinstance(value, list) and value and all(isinstance(x, str) for x in value):
                decls.append("    char *%s[] = {%s};" % (pname, ", ".join('"%s"' % x for x in value)))
                sizes[pname] = str(len(value))
            elif isinstance(value, list) and value and all(isinstance(x, list) for x in value):
                fixed = re.findall(r"\[(\d+)\]", raw)   # int m[][6] — inner size is fixed
                if "*" not in raw:
                    cols = int(fixed[-1]) if fixed else len(value[0])
                    rows_lit = ", ".join(c_int_literal(list(row) + [0] * (cols - len(row)), base)
                                         for row in value)
                    decls.append(f"    {base} {pname}[{len(value)}][{cols}] = {{{rows_lit}}};")
                else:                                     # int **m — rows plus a row-pointer array
                    row_names = []
                    for i, row in enumerate(value):
                        rows_prefix.append(f"    {base} {pname}_{i}[] = {c_int_literal(row, base)};")
                        row_names.append(f"{pname}_{i}")
                    decls.append(f"    {base} *{pname}[] = {{{', '.join(row_names)}}};")
                sizes[pname] = str(len(value))
                sizes["__cols_" + pname] = str(len(value[0]))
            else:
                return None
        elif ptr == 1:
            if isinstance(value, str):
                # a mutable buffer: several of these functions edit the string in place
                mutable = "const" not in raw
                decls.append(f'    {"char " + pname + "[]" if mutable else "const char *" + pname} = "{value}";')
                sizes[pname] = str(len(value))
            elif isinstance(value, list) and (
                    all(not isinstance(x, (list, str)) for x in value)
                    or (base == "char" and all(isinstance(x, str) and len(x) == 1 for x in value))):
                decls.append(f"    {base} {pname}[] = {c_int_literal(value, base)};")
                sizes[pname] = str(len(value))
            else:
                return None
        else:
            if base in ("bool", "_Bool"):
                decls.append(f"    bool {pname} = {'true' if value else 'false'};")
            elif base == "char" and isinstance(value, str):
                decls.append(f"    char {pname} = '{value}';")
            elif base in ("double", "float") and isinstance(value, (int, float)):
                decls.append(f"    {base} {pname} = {float(value)};")
            elif isinstance(value, int) and not isinstance(value, bool):
                decls.append(f"    {base} {pname} = {value};")
            else:
                return None
        args.append(pname)

    call = f"{name}({', '.join(args)})"
    body: list[str] = []
    if ret_raw.strip() == "void":
        body.append(f"    {call};")
        if buffers and out_size:
            body += ['    printf("[");',
                     f'    for (int i = 0; i < {out_size}; i++)',
                     f'        printf(i ? ",%lld" : "%lld", (long long) {buffers[0]}[i]);',
                     '    printf("]\\n");']
        elif not buffers:
            body += c_show_mutated(args, values, sizes)   # in place: show what changed
    elif ret_ptr >= 1 and ret_t == "char":
        body.append(f"    char *_r = {call};")
        body.append('    printf("%s\\n", _r ? _r : "");')
    elif ret_ptr >= 1:
        if not out_size:
            return None                     # an int* result needs its length from somewhere
        body.append(f"    int _n = 0;")
        body.append(f"    {ret_t} *_r = {call};")
        body.append(f"    _n = _out_{out_size};")
        body.append('    printf("[");')
        body.append('    for (int i = 0; i < _n; i++) printf(i ? ",%lld" : "%lld", (long long) _r[i]);')
        body.append('    printf("]\\n");')
    elif ret_t in ("bool", "_Bool"):
        body.append(f'    printf({call} ? "true\\n" : "false\\n");')
    elif ret_t in C_SCALAR and ret_t in ("int", "bool", "_Bool") and (
            re.match(r"(is|has|can|check|valid|contains|search|match)", name)
            or expected.strip().lower() in ("true", "false")):
        body.append(f'    printf({call} ? "true\\n" : "false\\n");')   # C has no bool return: show one
    elif ret_t in C_SCALAR:
        fmt = C_SCALAR[ret_t]
        cast = "(long long)" if "%ll" in fmt else ""
        body.append(f'    printf("{fmt}\\n", {cast} {call});')
    else:
        return None

    decls = rows_prefix + decls
    if out_size:
        decls.append(f"    int {out_size} = 0;")
    return ("\nint main(void) {\n" + "\n".join(decls) + "\n" + "\n".join(body)
            + "\n    return 0;\n}\n")


def c_int_literal(values, kind: str) -> str:
    """A C initialiser list: numbers, or characters (given as numbers or as 'x')."""
    if kind == "char":
        chars = [v if isinstance(v, str) else chr(int(v)) for v in values]
        return "{" + ", ".join("'%s'" % ch for ch in chars) + "}"
    return "{" + ", ".join(repr(v) for v in values) + "}"


C_STARTER = '''int main(void) {
    // TODO: read the input, compute, print the answer
    printf("0\\n");
    return 0;
}
'''


def c_starter(solution: str) -> str:
    src = strip_comments(solution)
    public = [sig for sig in c_signatures(src) if not sig[3]] or c_signatures(src)
    if not public:
        return C_STARTER
    ret, name, params, _ = public[0]
    stub = "    return NULL;" if "*" in ret else ("    return;" if ret.strip() == "void" else "    return 0;")
    return (f"{ret} {name}({params});   /* TODO: implement below, then call it from main */\n\n"
            f"{ret} {name}({params}) {{\n{stub}   /* TODO */\n}}\n\n"
            f"int main(void) {{\n"
            f"    /* call {name}(...) with the sample arguments and print the result */\n"
            f"    return 0;\n}}\n")


# --------------------------------------------------------------------------- #
#  main
# --------------------------------------------------------------------------- #
def load_c_sources() -> dict[str, str]:
    """site/leetcode/c/t<NN>_<topic>.py → {"slug": "C code"} (same files the bank pages use)."""
    code: dict[str, str] = {}
    c_dir = HERE / "c"
    if c_dir.is_dir():
        for path in sorted(c_dir.glob("t*.py")):
            spec = importlib.util.spec_from_file_location(path.stem, path)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)          # type: ignore[union-attr]
            for slug, src in getattr(mod, "CODE", {}).items():
                code.setdefault(slug, src.rstrip("\n") + "\n")
    return code


def main() -> int:
    c_code = load_c_sources()
    banks = []
    for path in sorted(HERE.glob("bank_*.py")):
        spec = importlib.util.spec_from_file_location(path.stem, path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)              # type: ignore[union-attr]
        banks.append({"topic": mod.TOPIC, "problems": mod.PROBLEMS})

    topics, problems = [], []
    stats = {"total": 0, "demo_py": 0, "demo_cpp": 0, "demo_java": 0, "demo_c": 0, "code_c": 0}
    for ti, bank in enumerate(banks, 1):
        topics.append({"n": ti, "name": bank["topic"]["name"], "tagline": bank["topic"]["tagline"]})
        for prob in bank["problems"]:
            stats["total"] += 1
            example = prob["examples"][0][0] if prob.get("examples") else ""
            want_c = prob["examples"][0][1] if prob.get("examples") else ""
            entry = {
                "slug": prob["slug"], "title": prob["title"], "difficulty": prob["difficulty"],
                "topic_n": ti, "topic": bank["topic"]["name"], "pattern": prob["pattern"],
                "statement": prob["statement"], "examples": prob.get("examples", []),
                "constraints": prob.get("constraints", []), "approach": prob["approach"],
                "complexity": list(prob["complexity"]),
                "code": {k: prob["code"][k] for k in ("cpp", "java", "python")},
                "starter": {}, "solution_run": {},
            }
            # ---- python
            demo = python_demo(prob["code"]["python"], example,
                               prob["code"]["cpp"] + prob["code"]["java"])
            entry["starter"]["python"] = python_starter(prob["code"]["python"])
            if demo:
                body = prob["code"]["python"].rstrip()
                entry["solution_run"]["python"] = python_prelude(body) + body + "\n\n" + demo + "\n"
                stats["demo_py"] += 1
            # ---- c++
            demo_cpp = cpp_demo(prob["code"]["cpp"], example)
            entry["starter"]["cpp"] = cpp_starter(prob["code"]["cpp"])
            if demo_cpp:
                entry["solution_run"]["cpp"] = prob["code"]["cpp"].rstrip() + "\n\n" + demo_cpp
                stats["demo_cpp"] += 1
            # ---- java
            demo_java = java_demo(prob["code"]["java"], example)
            entry["starter"]["java"] = java_starter(prob["code"]["java"])
            if demo_java:
                _, body = demo_java
                entry["solution_run"]["java"] = ("import java.util.*;\n\n"
                                                 "public class Main {\n"
                                                 + prob["code"]["java"].rstrip() + "\n\n"
                                                 "    public static void main(String[] args) {\n"
                                                 + "\n".join(body) + "\n"
                                                 "    }\n}\n")
                stats["demo_java"] += 1
            # ---- c
            src_c = c_code.get(prob["slug"], "")
            if src_c:
                entry["code"]["c"] = src_c
                stats["code_c"] += 1
                entry["starter"]["c"] = c_starter(src_c)
                demo_c = c_demo(src_c, example, want_c)
                if demo_c:
                    entry["solution_run"]["c"] = src_c.rstrip() + "\n" + demo_c
                    stats["demo_c"] += 1
            else:
                entry["code"]["c"] = ""
            problems.append(entry)

    payload = {"count": len(problems), "topics": topics, "problems": problems,
               "demos": {"python": stats["demo_py"], "cpp": stats["demo_cpp"],
                         "java": stats["demo_java"], "c": stats["demo_c"]}}
    OUT.write_text(json.dumps(payload, separators=(",", ":"), ensure_ascii=False))
    print(f"wrote {OUT.relative_to(SITE.parent)}  ({OUT.stat().st_size/1024/1024:.2f} MB)")
    print(f"  problems: {stats['total']}")
    print(f"  runnable demos: python {stats['demo_py']}/{stats['total']}"
          f" · c++ {stats['demo_cpp']}/{stats['total']} · java {stats['demo_java']}/{stats['total']}"
          f" · c {stats['demo_c']}/{stats['code_c']} written")
    print(f"  C solutions written: {stats['code_c']}/{stats['total']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
